### ISSUE TITLE
Project root alias

### ISSUE THREAD

**Issue by aaronmccall** [andreruffert/i18n-literally#7]
Hello Andre!

First of all, thank you for making this tool. I have been planning to follow this style of i18n implementation since reading the original article by @WebReflection.

In my current project, we are using babel-plugin-module-resolver with an alias to the project root (~).

This presents a problem because many imports in the project do not look like a relative import since they do not start with a dot.

Are you open to a merge request that adds the ability to pass --root and --rootAlias arguments so that aliased imports will resolve properly?

**Comment by andreruffert** [comment]
So far I never had the use case to alias import paths. 
For absolute import paths I was simply using `NODE_PATH` e.g.

```
$ NODE_PATH=src/ literally ./src/index.js de ./src/i18n.db.json
```

_src/index.js_

```js
import i18n from 'services/i18n.service';
import MyComponent from 'components/my-component';

// ...
```
etc.

---

For your example it would look something like this:

```
$ literally ./src/index.js de ./src/i18n.db.json --root=src --rootAlias=~/
```

_src/index.js_

```js
import i18n from '~/services/i18n.service';
import MyComponent from '~/components/my-component';

// ...
```
 
Is that correct?

**Comment by aaronmccall** [comment]
@andreruffert, I used 
`literally ./src/index.js de ./src/i18n.db.json --root=src --rootAlias=~` 
when I was testing, but the trailing slash may also work.
